version: '2.4'

services:
  dedoc:
    image: "dedocproject/dedoc:v2.2.1"
    ports:
        - 1231:1231

  test:
    build:
          context: .
          dockerfile: docker/Dockerfile
    environment:
      DEDOC_HOST: "dedoc"
    command:
      sh /podrostoc/tests/run_test.sh